name: Release

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  release:
    # Only run this workflow when a tag is pushed to the main branch
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: SBPC ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          body: |
            SBPC (Simple Bayesian Peak Caller) ${{ github.ref_name }}
            
            ## Installation
            
            ### Linux
            ```bash
            curl -L https://github.com/jakevc/sbpc/releases/download/${{ github.ref_name }}/sbpc-${{ github.ref_name }}-x86_64-unknown-linux-gnu.tar.gz | tar xz
            sudo mv sbpc /usr/local/bin/
            ```
            
            ### macOS
            ```bash
            curl -L https://github.com/jakevc/sbpc/releases/download/${{ github.ref_name }}/sbpc-${{ github.ref_name }}-x86_64-apple-darwin.tar.gz | tar xz
            sudo mv sbpc /usr/local/bin/
            ```
            
            ## Changes
            
            <!-- Release notes go here -->

  build-release:
    needs: release
    if: startsWith(github.ref, 'refs/tags/v')
    name: Build Release - ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ matrix.target }}

      - name: Install dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev pkg-config

      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Package binary
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          tar czvf ../../../sbpc-${{ github.ref_name }}-${{ matrix.target }}.tar.gz sbpc
          cd -

      - name: Upload binary to release
        uses: softprops/action-gh-release@v1
        with:
          files: sbpc-${{ github.ref_name }}-${{ matrix.target }}.tar.gz
          tag_name: ${{ github.ref_name }}

  build-and-push-docker:
    needs: release
    if: startsWith(github.ref, 'refs/tags/v')
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
