name: Test with Example Data

on:
  push:
    branches: [ main, "devin/*" ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pysam numpy

      - name: Generate test data
        run: |
          cd tests/data
          python generate_test_data.py --reads 5000 --peaks 5
          ls -la

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build SBPC
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Run SBPC on test data
        run: |
          ./target/release/sbpc -b tests/data/test_sample.bam -c tests/data/test_control.bam --metrics-file -r 1 --verbose > tests/data/test_sample_peaks.bed 
          
      - name: Display output metrics
        run: |
          echo "=== SBPC Output Metrics ==="
          cat test_sample_sbpc.json
          
          echo "=== SBPC Detected Peaks ==="
          head -n 10 tests/data/test_sample_peaks.bed
          
          echo "=== True Peaks (for comparison) ==="
          cat tests/data/test_true_peaks.bed
          
          echo "=== Peak Detection Statistics ==="
          echo "Number of detected peaks: $(wc -l < tests/data/test_sample_peaks.bed)"
          echo "Number of true peaks: $(wc -l < tests/data/test_true_peaks.bed)"
